#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker36"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "95209146461c40b0883a81d7ed9805a9" }
]

[assets]
directory = "./public"
